FROM node:20-slim AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html/
# vite.config.js is not needed for production build usually

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
